<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>Classic Models Employees</title>
	<link rel="stylesheet" type="text/css" href="form/view.css" media="all">
	<script type="text/javascript" src="form/view.js"></script>
</head>

<body id="main_body">

	<img id="top" src="form/top.png" alt="">
	<div id="form_container">
		<h1><a>Classic Models Employees</a></h1>
		<div class="form_description">
			<h2>Classic Model Cars Employees</h2>
			<p>No se ha podido eliminar el empleado debido a un error en BBDD.</p>
		</div>
		<ul>
			<li class="buttons">
				<a href='list.php'><img src='img/back_icon.png' width='25'></a>
			</li>
		</ul>
		<div id="footer">
			Generated by <a href="http://www.daw1.org">daw1</a>
		</div>
	</div>
	<img id="bottom" src="form/bottom.png" alt="">
</body>
</html>