<?php
require_once("autoload.php");

if ($_SERVER['REQUEST_METHOD'] == 'POST') {
	/* echo "<pre>";
		var_dump($_POST);
		echo "</pre>"; */
	if (
		isset($_POST['lastName']) && isset($_POST['firstName']) && isset($_POST['extension']) && isset($_POST['email'])
		&& isset($_POST['offices']) && isset($_POST['jefes']) && isset($_POST['jobTitle'])
	) {
		$lastName = $_POST['lastName'];
		$firstName = $_POST['firstName'];
		$extension = $_POST['extension'];
		$email = $_POST['email'];
		$office = $_POST['offices'];
		$jefe = $_POST['jefes'];
		$jobTitle = $_POST['jobTitle'];

		$data = [
			"lastName" => $lastName,
			"firstName" => $firstName,
			"extension" => $extension,
			"email" => $email,
			"officeCode" => $office,
			"reportsTo" => $jefe,
			"jobTitle" => $jobTitle
		];
		$cm = new ClassicModel();
		$cm->insert($data);
		header('Location: list.php');
	} else {
		print_r('No es posible crerar el nuevo empleado! Faltan datos.');
		die();
	}
}
?>
<!DOCTYPE html>
<html lang="en">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>Classic Models Employees</title>
	<link rel="stylesheet" type="text/css" href="form/view.css" media="all">
	<script type="text/javascript" src="form/view.js"></script>
</head>

<body id="main_body">

	<img id="top" src="form/top.png" alt="">
	<div id="form_container">

		<h1><a>Classic Models Employees</a></h1>
		<form class="appnitro" method="post" action="new.php">
			<div class="form_description">
				<h2>Classic Model Cars Employees</h2>
				<p>New Employee</p>
			</div>
			<ul>

				<li id="li_1">
					<label class="description" for="lastName">Last Name </label>
					<div>
						<input id="lastName" name="lastName" class="element text small" type="text" maxlength="255" value="" />
					</div>
				</li>
				<li id="li_2">
					<label class="description" for="firstName">First Name </label>
					<div>
						<input id="firstName" name="firstName" class="element text small" type="text" maxlength="255" value="" />
					</div>
				</li>
				<li id="li_3">
					<label class="description" for="extension">Extension </label>
					<div>
						<input id="extension" name="extension" class="element text small" type="text" maxlength="255" value="" />
					</div>
				</li>
				<li id="li_4">
					<label class="description" for="email">Email </label>
					<div>
						<input id="email" name="email" class="element text medium" type="text" maxlength="255" value="" />
					</div>
				</li>
				<li id="li_6">
					<label class="description" for="offices">Office </label>
					<div>
						<?php
						$c = new ClassicModel();
						echo $c->drawOfficesOptions();
						?>
					</div>
				</li>
				<li id="li_7">
					<label class="description" for="reportsTo">Reports To </label>
					<div>
						<?php
						$c = new ClassicModel();
						echo $c->drawEmployeesOptions();
						?>
					</div>
				</li>
				<li id="li_5">
					<label class="description" for="jobTitle">Job Title </label>
					<div>
						<input id="jobTitle" name="jobTitle" class="element text medium" type="text" maxlength="255" value="" />
					</div>
				</li>

				<li class="buttons">
					<input id="saveForm" class="button_text" type="submit" name="submit" value="Guardar" />
					<a href='list.php'><img src='img/back_icon.png' width='25'></a>
				</li>
			</ul>
		</form>
		<div id="footer">
			Generated by <a href="http://www.daw1.org">daw1</a>
		</div>
	</div>
	<img id="bottom" src="form/bottom.png" alt="">
</body>

</html>